const oldSearches = [
  {
    userId: 2,
    username: 'kazi',
    email: 'timonbeldi@gmail.com',
    gender: 'MALE',
    firstName: 'Timon',
    lastName: 'Beld',
  },
  {
    userId: 4,
    username: 'kazi2',
    email: 'timonbeldy@gmail.com',
    gender: 'MALE',
    firstName: null,
    lastName: null,
  },
  {
    userId: 5,
    username: 'kazi3',
    email: 'timonbelde@gmail.com',
    gender: 'MALE',
    firstName: null,
    lastName: null,
  },
  {
    userId: 7,
    username: 'kazi4',
    email: 'timonbeldm@gmail.com',
    gender: 'MALE',
    firstName: null,
    lastName: null,
  },
  {
    userId: 8,
    username: 'kazi4',
    email: 'timonbeldm@gmail.com',
    gender: 'MALE',
    firstName: null,
    lastName: null,
  },
  {
    userId: 9,
    username: 'kazi4',
    email: 'timonbeldm@gmail.com',
    gender: 'MALE',
    firstName: null,
    lastName: null,
  },
  {
    userId: 10,
    username: 'kazi10',
    email: 'timonbeldm@gmail.com',
    gender: 'MALE',
    firstName: null,
    lastName: null,
  },
];

export default oldSearches;
